### ISSUE TITLE
1.3.8 release breaks AWS opsworks

### ISSUE THREAD

**Issue by Entr04y** [opscode-cookbooks/windows#252]
The 1.3.8 release includes the source_url directive in metadata.rb.  AWS opsworks only supports up to chef 11.10 on linux stacks, and the elastic search recipe depends on ark, which depends on windows and pulls in the latest version.  

Here is the error message from opsworks:

ERROR: Could not read /opt/aws/opsworks/current/merged-cookbooks/windows into a Chef object: undefined method `source_url' for #<Chef::Cookbook::Metadata:0x007febed0115e0>

The 1.3.7 release works fine.

Edit:  The source_url parameter is in the metadata.json file in 1.37.0 also, but there is no metadata.rb file in that version (at least when pulled into opsworks via Berkshelf) so the difference appears to be including that parameter in metadata.rb.

**Comment by tringuyen** [comment]
Seeing the same thing on our stack. I think we need a fix similar to below to be backwards compatible with Chef < 12

https://github.com/redguide/nodejs/pull/79/files

**Comment by jaym** [comment]
I published 1.38.1 without source_url and issue_url. Can you try again

**Comment by tringuyen** [comment]
I still see source_url and issue_url in the metadata. I only see changes to the changelog Did the change actually go through?

**Comment by jaym** [comment]
It was published without

**Comment by JamesMGreene** [comment]
:+1: Totally killing my OpsWorks stack... yaaaaay. :unamused:
